code verified and test cases added using Xunit
Kount/kount-ris-dotnet-core-sdk pull request #1
Opened 2020-04-09 05:16 UTC by bingyansa

Code changes have been done for kount-ris-dotnet-core-sdk. Configuration values can be read from appsettings.json file instead of app.config.
Test cases are implemented using xUnit.

2020-04-15 13:59 UTC, gjd-keynetics requested changes
Overall it looks good.  There are some commented out tests that should either be:

1. Removed
2. Re-enabled
3. Documented at the top of the comment block as to why they will stay commented out for now.

Also I notices a few documentation files that looked autogenerated, but had no content yet.  That is fine for now, but they should be cleaned up or removed prior to a release.

2020-04-15 13:59 UTC, gjd-keynetics commented on KountRisCoreConfigTest/InquiryTest.cs
> +        //[Fact]
If you don't plan on running this test anymore it should be removed and not commented out.  If the comment is temporary and waiting on another PR, it should be documented at the top of of the comment block

2020-04-15 13:59 UTC, gjd-keynetics commented on KountRisCoreTest/BasicConnectivityTest.cs
> +        // [Fact]
Same as before, if not used remove, otherwise re-enable or document why it's disabled for now.

2020-04-15 13:59 UTC, gjd-keynetics commented on KountRisCoreTest/MaskInquiryTest.cs
> +        //[Fact]
Same as before

2020-06-10 18:24 UTC, bingyansa commented on KountRisCoreTest/MaskInquiryTest.cs
> +        //[Fact]
Hi @gjd-keynetics , As you mentioned above points, changes have been implemented and log4net is also implemented in this code. Previously FileStream was there and it replaced with log4net.

2020-06-10 19:32 UTC, gjd-keynetics requested changes
I need some clarification on whether we are stopping the testing of mode J (two of these tests were removed) in addition to the Kount Central test is still disabled.  If we are not supposed to test these anymore, I will approve it.  Otherwise we need to add back in or uncomment them.  If there is a valid reason for removing them, I will change my response to Approve.

2020-06-10 19:32 UTC, gjd-keynetics commented on KountRisCoreTest/BasicConnectivityTest.cs
> -
Is this test still being performed somewhere?  I believe we still get Mode J requests. If we are no longer supporting Mode J, or this test is being performed in another area, I am fine with it being removed.

2020-06-10 19:32 UTC, gjd-keynetics commented on KountRisCoreTest/MaskInquiryTest.cs
> +        //[Fact]
this test does not look like its testing the logging, it looks like it is testing the Kount Central Rules.  It should not be commented out AFAIK.

2020-06-10 19:32 UTC, gjd-keynetics commented on KountRisCoreConfigTest/InquiryTest.cs
> -        /// <summary>
Are we not testing Mode J anymore, or is this being tested someplace else?

2020-06-10 19:37 UTC, bingyansa commented on KountRisCoreConfigTest/InquiryTest.cs
> -        /// <summary>
> Are we not testing Mode J anymore, or is this being tested someplace else?

@gjd-keynetics, For Mode J we are not getting any response. So in Java also we commented them.

2020-06-10 20:20 UTC, gjd-keynetics approved these changes

2020-06-10 20:30 UTC, toddfunke approved these changes

2020-06-10 20:33 UTC, merged